[project]
name = "the-song-of-ducks-and-dragons"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bpython>=0.26",
    "pudb>=2025.1.3",
]
